/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

/**
 *
 * @author Eduardo
 */
public class Principal extends javax.swing.JFrame {

int total=0;
    
    public Principal() {
        initComponents();
        painel1.setVisible(true);
            painel2.setVisible(false);
              painel3.setVisible(false);
                painel4.setVisible(false);
                    painel8.setVisible(false);
                        sefu.setVisible(false);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        painel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        painel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        enviar1 = new javax.swing.JButton();
        resp1 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        painel3 = new javax.swing.JPanel();
        painel6 = new javax.swing.JPanel();
        enviar2 = new javax.swing.JButton();
        resp2 = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        painel4 = new javax.swing.JPanel();
        painel7 = new javax.swing.JPanel();
        enviar3 = new javax.swing.JButton();
        resp3 = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bom = new javax.swing.JPanel();
        painel8 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        acert = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        sefu = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painel1.setBackground(new java.awt.Color(0, 0, 255));

        jButton1.setText("Jogar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Vani", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setText("              Game Birl");

        javax.swing.GroupLayout painel1Layout = new javax.swing.GroupLayout(painel1);
        painel1.setLayout(painel1Layout);
        painel1Layout.setHorizontalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        painel1Layout.setVerticalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        getContentPane().add(painel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        painel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("Escolha a opção que nomeia a foto");
        painel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1.png"))); // NOI18N
        painel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        enviar1.setText("Enviar");
        enviar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviar1ActionPerformed(evt);
            }
        });
        painel2.add(enviar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 120, 50));

        resp1.setModel(new javax.swing.SpinnerNumberModel(2, 1, 2, 1));
        painel2.add(resp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 80, 30));

        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("2-Adolf Birl");
        painel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Selecione");
        painel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 70, 30));

        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("1-Osama Birl Ladem");
        painel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        getContentPane().add(painel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        painel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enviar2.setText("Enviar");
        enviar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviar2ActionPerformed(evt);
            }
        });
        painel6.add(enviar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 120, 40));

        resp2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 3, 1));
        painel6.add(resp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 80, 30));

        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("3-Steve Jovem");
        painel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("Selecione");
        painel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 70, 30));

        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("1-Bil Gates");
        painel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("2-Birl Gates");
        painel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2.jpg"))); // NOI18N
        painel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 150, 160));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 255));
        jLabel7.setText("Quem é o atual dono da MicroBirl?");
        painel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        painel3.add(painel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(painel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        painel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enviar3.setText("Enviar");
        enviar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviar3ActionPerformed(evt);
            }
        });
        painel7.add(enviar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 120, 40));

        resp3.setModel(new javax.swing.SpinnerNumberModel(1, 1, 3, 1));
        painel7.add(resp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 80, 30));

        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("3-Justin Bielrbson");
        painel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel16.setForeground(new java.awt.Color(0, 0, 255));
        jLabel16.setText("Selecione");
        painel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 70, 30));

        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setText("1-The Birlthles");
        painel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 80, -1));

        jLabel18.setForeground(new java.awt.Color(153, 153, 153));
        jLabel18.setText("2-Calybirlson");
        painel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3.jpg"))); // NOI18N
        painel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 150, 80));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 255));
        jLabel10.setText("Qual o nome da banda?");
        painel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        painel4.add(painel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 290));

        getContentPane().add(painel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        painel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/hqdefault.jpg"))); // NOI18N
        painel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 270));

        acert.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        acert.setText("0");
        painel8.add(acert, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 274, 20, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Acertos");
        painel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 80, 20));

        javax.swing.GroupLayout bomLayout = new javax.swing.GroupLayout(bom);
        bom.setLayout(bomLayout);
        bomLayout.setHorizontalGroup(
            bomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bomLayout.setVerticalGroup(
            bomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(bom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        sefu.setBackground(new java.awt.Color(255, 0, 0));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sef.jpg"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Vrinda", 0, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Se Fodeu");

        javax.swing.GroupLayout sefuLayout = new javax.swing.GroupLayout(sefu);
        sefu.setLayout(sefuLayout);
        sefuLayout.setHorizontalGroup(
            sefuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sefuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addGap(25, 25, 25))
        );
        sefuLayout.setVerticalGroup(
            sefuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sefuLayout.createSequentialGroup()
                .addGroup(sefuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sefuLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel19))
                    .addGroup(sefuLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        getContentPane().add(sefu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        painel2.setVisible(true);
        painel1.setVisible(false);
        painel3.setVisible(false);
        painel4.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void enviar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviar1ActionPerformed
        
        int a =(int) resp1.getValue();
        
               if(a == 1){
            System.out.println("Certo");
            total+=1;
                   System.out.println(total);
        }else{
            System.out.println("Errado");
        }
        painel1.setVisible(false);
        painel2.setVisible(false);
        painel3.setVisible(true);
        painel4.setVisible(false);
    }//GEN-LAST:event_enviar1ActionPerformed

    private void enviar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviar2ActionPerformed
        int b = (int) resp2.getValue();
        total += (b == 2 ) ? 1 : 0;
        System.out.println(total);
        
        painel1.setVisible(false);
        painel2.setVisible(false);
        painel3.setVisible(false);
        painel4.setVisible(true);

    }//GEN-LAST:event_enviar2ActionPerformed

    private void enviar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviar3ActionPerformed
         int c = (int) resp3.getValue();
        total += (c == 1 ) ? 1 : 0;
        System.out.println(total);
        
        painel1.setVisible(false);
        painel2.setVisible(false);
        painel3.setVisible(false);
        painel4.setVisible(false);
        if(total >= 2){
         painel8.setVisible(true);
        }else{
         sefu.setVisible(true);
        }
        acert.setText(Integer.toString(total));
    }//GEN-LAST:event_enviar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acert;
    private javax.swing.JPanel bom;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton enviar1;
    private javax.swing.JButton enviar2;
    private javax.swing.JButton enviar3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel painel1;
    private javax.swing.JPanel painel2;
    private javax.swing.JPanel painel3;
    private javax.swing.JPanel painel4;
    private javax.swing.JPanel painel6;
    private javax.swing.JPanel painel7;
    private javax.swing.JPanel painel8;
    private javax.swing.JSpinner resp1;
    private javax.swing.JSpinner resp2;
    private javax.swing.JSpinner resp3;
    private javax.swing.JPanel sefu;
    // End of variables declaration//GEN-END:variables
}
